---
user_config_yml: user.config.yml

###
## MAC OS
#
homebrew_packages:
  - autoconf
  - clang-format
  - coreutils
  - curl
  - cowsay
  - direnv
  - fzf
  - git
  - mas
  - neovim
  - npm
  - python
  - ripgrep
  - shellcheck
  - the_silver_searcher
  - zoxide
  - zsh

homebrew_cask_appdir: /Applications
homebrew_cask_accept_external_apps: false

homebrew_cask_packages:
  - docker
  - dropbox
  - font-inconsolata-nerd-font
  - font-meslo-lg-nerd-font
  - font-sauce-code-pro-nerd-font
  - iterm2

homebrew_taps:
  - homebrew/core
  - homebrew/cask

###
## Other packages
##
pip_packages:
  - ansible-lint

###
## .dotfiles packages
#
devenv_enabled: true
git_enabled: true
nvim_enabled: true
themes_enabled: true
vim_enabled: false
zsh_enabled: true
