---
user_config_yml: user.config.yml

###
## MAC OS
#
homebrew_packages:
  - coreutils
  - cowsay
  - clang-format
  - direnv
  - fzf
  - git
  - mas
  - neovim
  - npm
  - python
  - ripgrep
  - the_silver_searcher
  - zoxide
  - zsh

homebrew_cask_appdir: /Applications

homebrew_cask_packages:
  - docker
  - iterm2

homebrew_taps:
  - homebrew/core
  - homebrew/cask

###
## .dotfiles packages
#
git_enabled: true
nvim_enabled: true
zsh_enabled: true
