---
- name: Provision system
  hosts: all
  vars_files:
    - default.config.yml
  pre_tasks:
    - name: "Optional include {{ user_config_yml }}"
      ansible.builtin.include_vars: "{{ user_config_yml }}"
      when: user_config_yml is exists
      tags: ['always']

  roles:
    - role: roles/macos
      when: ansible_os_family == "Darwin"
      tags: system

    - role: roles/devenv
      tags: devenv
      when: devenv_enabled

    - role: roles/git
      tags: packages, git
      when: git_enabled

    - role: roles/nvim
      tags: packages, nvim
      when: nvim_enabled

    - role: roles/themes
      tags: packages, themes
      when: themes_enabled

    - role: roles/vim
      tags: packages, vim
      when: vim_enabled

    - role: roles/zsh
      tags: packages, zsh
      when: zsh_enabled

# vim: ft=yaml.ansible
