---
- name: Provision system
  hosts: all
  vars_files:
    - default.config.yml
  pre_tasks:
    - name: "Optional include {{ user_config_yml }}"
      ansible.builtin.include_vars: "{{ user_config_yml }}"
      when: user_config_yml is exists
      tags: ['always']

  roles:
    - role: roles/homebrew
      when: ansible_os_family == "Darwin"
      tags: homebrew

    - role: roles/nvim
      tags: packages, nvim
      when: nvim_enabled

    - role: roles/git
      tags: packages, git
      when: git_enabled

    - role: roles/zsh
      tags: packages, zsh
      when: zsh_enabled

  tasks:
    - import_tasks: tasks/macos_settings.yml
      when: ansible_os_family == "Darwin"
      tags: macos_settings

# vim: ft=yaml.ansible
