---
- name: "Brew:taps"
  homebrew_tap:
    tap: "{{ item | default(item) }}"
    url: "{{ item | default(omit) }}"
    state: present
  loop: "{{ homebrew_taps }}"

- name: "Brew:packages"
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ homebrew_packages }}"

- name: "Brew:cask packages"
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: present
    install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
    accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  loop: "{{ homebrew_cask_packages }}"

# vim: ft=yaml.ansible
