#!/usr/bin/env bash
set -e

# This isn't expected to be run standalone, but can be if necessary
[ -n "$DOT_OS" ] || fail "DOT_OS not defined"

required_binaries=("zsh" "git" "nvim" "fzf" "zoxide")

# TODO npm ripgrep

mac_packages_core=(coreutils git)
apt_packages_core=(build-essential curl file git procps)

brew_packages_core=(direnv fzf git neovim python the_silver_searcher zoxide zsh)

# llvm on OS X conflicts with Apple version, but clang-format on linux conflicts with llvm
brew_packages_extra_macos=(clang-format)
brew_packages_extra_linux=(llvm)

install_brew() {
	log "Checking for brew..."
	if [ -z "$(command -v brew)" ] ; then
		log "Installing brew..."
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
		eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
	fi
	log "Update brew" && brew update --quiet
}

install() {
	log "Installing $*"
	brew install --quiet $*
}

dot_system_packages() {
	if [ "macos" = "$DOT_OS" ] ; then
		install_brew
		install ${mac_packages_core[*]}
		extras=$brew_packages_extra_macos
	else
		log "Update apt" && sudo apt-get update
		log "Installing ${apt_packages_core[*]}" && sudo apt-get install -y ${apt_packages_core[*]}
		install_brew
		extras=$brew_packages_extra_linux
	fi

	install ${brew_packages_core[*]}
	install ${extras[*]}
}

