#!/usr/bin/env bash
set -e

# This isn't expected to be run standalone, but can be if necessary
[ -n "$DOT_OS" ] || fail "DOT_OS not defined"

required_binaries=("zsh" "git" "nvim" "fzf" "zoxide")

mac_packages_core=(coreutils git)
apt_packages_core=(build-essential curl file git procps)

brew_packages_core=(fzf git neovim python zoxide zsh)
brew_packages_extra=(clang-format direnv the_silver_searcher)


install_brew() {
	if [ -x "$(command -v brew)" ] ; then
		log "Installing brew..."
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	fi
	log "Update brew" && brew update
}

install() {
	log "Installing $*"
	brew install $*
}

dot_system_packages() {
	if [ "macos" = "$DOT_OS" ] ; then
		install_brew
		install ${mac_packages_core[*]}
	else
		log "Update apt" && sudo apt-get update
		log "Installing ${apt_packages_core[*]}" && sudo apt-get install -y ${apt_packages_core[*]}
		install_brew
	fi

	install ${brew_packages_core[*]}
	install ${brew_packages_extra[*]}
}

