---
- name: Install symlinks
  ansible.builtin.include_tasks: tasks/symlink.yml
  with_items: "{{ nvim_symlinks }}"

- name: Cleanup plugged remnants
  file:
    path: "~/.local/share/nvim/plugged"
    state: absent

- name: Cleanup packer remnants
  file:
    path: "~/.local/share/nvim/site/pack"
    state: absent

# vim: ft=yaml.ansible
